default:
  image: node:15.14.0-alpine3.10

stages:
  - build
  - test
  - docker-build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
build:
  stage: build
  image: node:15.14.0-alpine3.10
  tags:
    - gitlab-react

  script:
    - echo "Start building App"
    - yarn install
    - CI=false yarn build
    - echo "Build successfully!"

  artifacts:
    expire_in: 2 hour
    paths:
      - build
      - node_modules/
test_feature_branch:
  stage: test
  image: node:15.14.0-alpine3.10
  tags:
    - gitlab-react

  only:
    - /^feature-.*$/
  script:
    - echo "Testing App"
    - CI=false yarn test
    - yarn coverage
    - echo "Test successfully!"

test_master_branch:
  stage: test
  image: node:15.14.0-alpine3.10
  tags:
    - gitlab-react

  script:
    - echo "Testing App"
    - CI=false yarn test
    - yarn coverage
    - echo "Test successfully!"

docker-build:
  stage: docker-build
  image: docker:latest
  tags:
    - gitlab-react
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    - docker rmi $TAG_COMMIT

  only:
    refs:
      - master

deploy-firebase:
  stage: deploy
  tags:
    - gitlab-react
  image: node:15.14.0-alpine3.10
  before_script:
    - echo "deploying app to firebase"

  script:
    - npm i -g firebase-tools
    - CI=false yarn build
    - firebase deploy --token "$FIREBASE_TOKEN"
  only:
    refs:
      - master
