import { IInitState, UserRole } from "./types";
export const initialState: IInitState = {
  isLoading: false,
  isFaliure: false,
  currentUser: {
    email: "",
    role: UserRole.DEFAULT,
    uid: "",
    userName: "",
  },
  authenticated: false,
  client: {
    companyName: "",
    companyUrl: "",
    phoneNumber: "",
    email: "",
    tinNumber: "",
    id: "",
    service: "",
    address: { country: "", city: "", subCity: "" },
    business: "",
    password: "",
    role: "",
    city: "",
    subCity: "",
    verification_status: "",
  },
  clients: [],
  selectedUserData: [],
};
